### ISSUE TITLE
No handler found 

### ISSUE THREAD

**Issue by pliski** [AnWeber/vscode-tidyhtml#1]
```
Ctrl+P

ext install vscode-tidyhtml
```

restarted vsCode

`F1 TidyHtml`

and I got this message:

> Error - No handler found for the command: 'extension.tidyHtml'. An extension might be missing an activation event.

Environment:
_ vsCode Version 1.0.0
_ Ubuntu 15.10

**Comment by trong291990** [comment]
Same problem
Ubuntu 16.04

**Comment by AnWeber** [comment]
hello,

thanks for your issue report. Sorry for the long delay. I needed a break. I can't reproduce the issue on my windows machine. I will install a ubuntu as virtual machine and try again.

**Comment by AnWeber** [comment]
While activating my extension, vscode throws an error:

[Extension Host] Here is the error stack:  Error: Cannot find module './TidyWorker'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.I.n._load (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:25921)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/andreas/.vscode/extensions/anweber.vscode-tidyhtml-0.0.4/out/src/Formatter.js:5:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

I will try to fix it.

**Comment by AnWeber** [comment]
in version 0.1.0 it is fixed. Wish you a nice sunny afternoon.
